package com.jobmatchai.backend.service;

import com.jobmatchai.backend.service.AIChatContextService.CanonicalFact;
import com.jobmatchai.backend.util.SkillClaimMatcher;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

// The chat assistant's reply is free text generated by a second, independent LLM call from the
// SAME class of risk as computeJobMatchDetail's narrative (see JobMatchService#validateDetailClaims):
// it is handed the canonical CanonicalFact data as prompt context, but nothing stops it from
// paraphrasing its way into a claim that contradicts that data (e.g. praising a skill the
// canonical row lists as missing, or stating a match percentage the canonical row doesn't have).
// Unlike validateDetailClaims, this doesn't operate on a fixed set of discrete AI-returned arrays
// scoped to one job - a chat reply is one markdown-templated string (see AIChatService's
// responseFormatTemplate) that can discuss any number of the jobs/candidates it was given, so this
// parses that structure itself: "## Heading" sections, "- " bullets, and "**NN%**" percentages.
//
// Two kinds of contradiction are handled differently, matching how confidently each can be fixed
// without another AI call:
//   - A wrong PERCENTAGE is corrected in place (rewritten to the canonical number) - there's only
//     one right number, so silently repairing it is strictly better than dropping the whole line.
//   - A skill claim that contradicts the canonical matched/missing lists is DROPPED (the bullet
//     making the claim is removed), mirroring validateDetailClaims - there's no single "correct"
//     rewrite for a sentence that got the substance wrong, only an incorrect one to remove.
//
// A wrong percentage inside the dedicated "## Match Score" section (the template's single most
// prominent, structurally guaranteed claim) is flagged CRITICAL: the caller (see AIChatService)
// uses that to decide whether the reply is worth one regeneration attempt with corrective
// feedback, rather than only silently patching the number and moving on.
@Service
public class ChatConsistencyValidator {

    private static final Logger log = LoggerFactory.getLogger(ChatConsistencyValidator.class);

    private static final Pattern HEADING_PATTERN = Pattern.compile("^##\\s+(.+?)\\s*$");
    private static final Pattern PERCENT_PATTERN = Pattern.compile("\\*\\*(\\d{1,3})%\\*\\*");

    // Section headings under which naming a MISSING skill is expected/correct behavior (the
    // template's own example uses a "## Missing Skills" heading for exactly this) - the
    // "praises a missing skill" check below only applies OUTSIDE these headings, since inside them
    // citing a missing skill is the whole point, not a contradiction.
    private static final List<String> NEGATIVE_HEADING_KEYWORDS = List.of("missing", "weakness", "gap", "concern");

    public record ValidationResult(String reply, List<String> issues, boolean critical) {}

    public ValidationResult validate(String reply, List<CanonicalFact> facts) {
        if (reply == null || reply.isBlank() || facts == null || facts.isEmpty()) {
            return new ValidationResult(reply, List.of(), false);
        }

        List<String> issues = new ArrayList<>();
        boolean[] critical = {false};

        List<Block> blocks = splitIntoBlocks(reply);

        CanonicalFact runningFocus = facts.size() == 1 ? facts.get(0) : null;
        for (Block block : blocks) {
            CanonicalFact blockFact = matchFactInText(block.headingText() + "\n" + String.join("\n", block.bodyLines()), facts);
            if (blockFact != null) {
                runningFocus = blockFact;
            }
            block.focus = runningFocus;
        }

        StringBuilder rebuilt = new StringBuilder();
        for (Block block : blocks) {
            boolean isMatchScoreHeading = block.headingText() != null
                    && block.headingText().trim().equalsIgnoreCase("Match Score");
            boolean isNegativeHeading = block.headingText() != null
                    && NEGATIVE_HEADING_KEYWORDS.stream().anyMatch(block.headingText().toLowerCase(Locale.ROOT)::contains);

            List<String> newBody = new ArrayList<>();
            int originalBulletCount = 0;
            int keptBulletCount = 0;

            for (String line : block.bodyLines()) {
                String trimmed = line.trim();
                boolean isBullet = trimmed.startsWith("-");
                if (isBullet) {
                    originalBulletCount++;
                }

                if (trimmed.isEmpty()) {
                    newBody.add(line);
                    continue;
                }

                CanonicalFact lineFact = matchFactInText(trimmed, facts);
                CanonicalFact active = lineFact != null ? lineFact : block.focus;
                if (active == null) {
                    newBody.add(line);
                    if (isBullet) {
                        keptBulletCount++;
                    }
                    continue;
                }

                String corrected = correctPercent(line, active, issues);
                if (isMatchScoreHeading && !corrected.equals(line)) {
                    critical[0] = true;
                }
                line = corrected;

                if (isBullet) {
                    String lower = line.toLowerCase(Locale.ROOT);
                    boolean drop = false;

                    if (!isNegativeHeading) {
                        boolean praisesMissingSkill = active.missingSkills().stream()
                                .anyMatch(skill -> SkillClaimMatcher.mentionsSkill(lower, skill));
                        if (praisesMissingSkill) {
                            issues.add("dropped a reply bullet praising '" + active.jobTitle()
                                    + "'-missing skill as a strength (contradicts the validated missing-skills list)");
                            log.info("chat-reply-filtered reason=praises-missing-skill jobId={}", active.jobId());
                            drop = true;
                        }
                    }

                    if (!drop) {
                        boolean flagsMatchedSkillAsAbsent = SkillClaimMatcher.hasGenuineAbsenceClaim(lower)
                                && active.matchedSkills().stream().anyMatch(skill -> SkillClaimMatcher.mentionsSkill(lower, skill));
                        if (flagsMatchedSkillAsAbsent) {
                            issues.add("dropped a reply bullet flagging a '" + active.jobTitle()
                                    + "'-matched skill as a gap (contradicts the validated matched-skills list)");
                            log.info("chat-reply-filtered reason=flags-matched-skill-as-gap jobId={}", active.jobId());
                            drop = true;
                        }
                    }

                    if (drop) {
                        continue;
                    }
                    keptBulletCount++;
                }

                newBody.add(line);
            }

            // A heading whose every bullet got dropped is worse than no heading at all (an empty
            // "## Strengths" card with nothing under it) - "## Match Score"/"## Summary" never
            // reach here empty since their content isn't bulleted and is only ever number-corrected
            // above, never dropped.
            boolean sectionEmptied = originalBulletCount > 0 && keptBulletCount == 0
                    && newBody.stream().allMatch(String::isBlank);

            if (block.headingText() != null && !sectionEmptied) {
                rebuilt.append("## ").append(block.headingText()).append("\n");
            } else if (block.headingText() != null) {
                issues.add("dropped the entire '" + block.headingText() + "' section - every claim in it contradicted validated data");
            }
            if (!sectionEmptied) {
                for (String line : newBody) {
                    rebuilt.append(line).append("\n");
                }
            }
        }

        String correctedReply = rebuilt.toString().stripTrailing();
        return new ValidationResult(correctedReply, issues, critical[0]);
    }

    private String correctPercent(String line, CanonicalFact fact, List<String> issues) {
        if (fact.matchPercent() == null) {
            return line;
        }
        Matcher matcher = PERCENT_PATTERN.matcher(line);
        StringBuilder result = new StringBuilder();
        boolean changed = false;
        while (matcher.find()) {
            int claimed = Integer.parseInt(matcher.group(1));
            if (claimed != fact.matchPercent()) {
                changed = true;
                matcher.appendReplacement(result, Matcher.quoteReplacement("**" + fact.matchPercent() + "%**"));
            } else {
                matcher.appendReplacement(result, Matcher.quoteReplacement(matcher.group()));
            }
        }
        matcher.appendTail(result);
        if (changed) {
            issues.add("corrected a match-percentage claim for '" + fact.jobTitle()
                    + "' to the validated " + fact.matchPercent() + "%");
        }
        return result.toString();
    }

    // Resolves which single CanonicalFact `text` is talking about. Deliberately conservative: if
    // more than one distinct fact's job title (and, in company mode, candidate name) plausibly
    // matches, this returns null (ambiguous) rather than guessing - a wrong "correction" driven by
    // a bad guess would itself be a new contradiction, which defeats the entire point. This means a
    // reply that discusses several same-titled jobs or several candidates for one job in a single
    // bullet without repeating identifying names won't get validated - see this class's own
    // known-limitations note in ChatConsistencyValidatorTest / the audit summary.
    private CanonicalFact matchFactInText(String text, List<CanonicalFact> facts) {
        if (text == null || text.isBlank()) {
            return null;
        }
        String lower = text.toLowerCase(Locale.ROOT);
        CanonicalFact found = null;
        for (CanonicalFact fact : facts) {
            boolean titleHit = fact.jobTitle() != null && fact.jobTitle().trim().length() >= 3
                    && lower.contains(fact.jobTitle().toLowerCase(Locale.ROOT).trim());
            boolean nameHit = fact.candidateName() == null
                    || (fact.candidateName().trim().length() >= 3 && lower.contains(fact.candidateName().toLowerCase(Locale.ROOT).trim()));
            if (titleHit && nameHit) {
                if (found != null && !found.equals(fact)) {
                    return null;
                }
                found = fact;
            }
        }
        return found;
    }

    // Not a record: needs a mutable `focus` field assigned in a second pass after all blocks are
    // known (see validate's two-pass loop), which a record's immutable components can't hold.
    private static final class Block {
        private final String headingText;
        private final List<String> bodyLines;
        private CanonicalFact focus;

        private Block(String headingText, List<String> bodyLines) {
            this.headingText = headingText;
            this.bodyLines = bodyLines;
        }

        private String headingText() {
            return headingText;
        }

        private List<String> bodyLines() {
            return bodyLines;
        }
    }

    private List<Block> splitIntoBlocks(String reply) {
        List<Block> blocks = new ArrayList<>();
        String currentHeading = null;
        List<String> currentBody = new ArrayList<>();

        for (String line : reply.split("\n", -1)) {
            Matcher headingMatcher = HEADING_PATTERN.matcher(line.trim());
            if (headingMatcher.matches()) {
                blocks.add(new Block(currentHeading, currentBody));
                currentHeading = headingMatcher.group(1).trim();
                currentBody = new ArrayList<>();
            } else {
                currentBody.add(line);
            }
        }
        blocks.add(new Block(currentHeading, currentBody));
        return blocks;
    }
}
