spring.application.name=backend

spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?pgbouncer=true&sslmode=require&preparedStatementCacheQueries=0&preparedStatementCacheSizeMB=0

spring.datasource.username=postgres.cgoiysaabmavfqzuwvuf

spring.datasource.password=bayanbian123

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
openai.api.key=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
openai.api.url=https://api.openai.com/v1/responses
openai.model=gpt-4.1